clients:
  ports:
    node_exporter: 9100
    blockchain_exporter: 9877
    cadvisor: 8080
    promtail: 9080
    loki: 3100

server:
  endpoint: 147.182.131.254
  ports:
    loki: 3100
    prometheus: 9090
    grafana: 3000
    minio: 9000
    promtail: 9080
  slack:
    webhook: https://hooks.slack.com/services/your_slack_webhook_string
  exporter_endpoints:
    cadvisor: ["147.182.173.249:8080"]
    blockchain: ["147.182.173.249:9877"]
    node: ["147.182.173.249:9100"]
