clients:
  ports:
    node_exporter: 9100
    blockchain_exporter: 9877
    cadvisor: 8080
    promtail: 9080
    loki: 3100
  promtail_log_root_path: ./log

server:
  endpoint: 111.222.333.001
  ports:
    loki: 3100
    prometheus: 9090
    grafana: 3000
    minio: 9000
    promtail: 9080
  alerts:
    interval: 60s
    contactpoints:
      slack:
        enabled: False
        url: https://hooks.slack.com/services/your_slack_webhook_string
      discord:
        enabled: False
        url: https://discord.com/api/webhooks/your_uuid/your_other_uuid
      teams:
        enabled: False
        url: https://ms_teams_url
      email:
        enabled: False
        addresses: ["me@example.com", "you@example.com"]

  exporter_endpoints:
    cadvisor: [ "111.222.333.002:8080" ]
    blockchain: [ "111.222.333.002:9877" ]
    node: [ "111.222.333.002:9100" ]