server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

# local machine logs
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
    pipeline_stages:
      - match:
          pipeline_name: 'relay'
          selector: '{job="varlogs"} |~ ".*/v1/client/relay.*"'
          stages:
            - json:
                expressions:
                  timestamp: time_local
                  status: status
                  region: region
                  request_body:
                drop_malformed: true
            - json:
                expressions:
                  proof:
                source: request_body
                drop_malformed: true
            - json:
                expressions:
                  blockchain:
                source: proof
                drop_malformed: true
            - labels:
                timestamp:
                status:
                blockchain:
                region:
