# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'pokt'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

#  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
#    scrape_interval: 15s

#    static_configs:
#         - targets: ['localhost:9090']

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node_exporter:9100']

  - job_name: blockchain
    scrape_interval: 5s
    static_configs:
    - targets: ['blockchain_exporter:9877']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: poktnodes
    scrape_interval: 5s
    static_configs:
      - targets: ['poktnodes:80']

    metric_relabel_configs:
      # Create host label for all metrics
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0(.*)"
        replacement: "${1}"
        target_label: "chain_id"
        action: "replace"
      # Create chain_id label for all pocketcore_service_relay_count metrics
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0(.*)"
        replacement: "${1}"
        target_label: "chain_id"
        action: "replace"
      # Create chain_name label for all metrics
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0(.*)"
        replacement: "${1}"
        target_label: "chain_name"
        action: "replace"

      # Update chain_name for each chain separately
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0029"
        replacement: "Algorand"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_000D"
        replacement: "Algorand Arch"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0045"
        replacement: "Algorand Test"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0A45"
        replacement: "Algorand Test Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0003"
        replacement: "Avax"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_00A3"
        replacement: "Avax Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0004"
        replacement: "BSC"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0010"
        replacement: "BSC Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0021"
        replacement: "ETH"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0022"
        replacement: "ETH Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0027"
        replacement: "xDai"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0028"
        replacement: "ETH Arch Trace"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0026"
        replacement: "ETH Goreli"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0024"
        replacement: "ETH Kovan"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0025"
        replacement: "ETH Rinkeby"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0023"
        replacement: "ETH Ropston"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0005"
        replacement: "Fuse"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_000A"
        replacement: "Fuse Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_000C"
        replacement: "xDai Arch."
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0040"
        replacement: "ONE"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0044"
        replacement: "IoTeX"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0046"
        replacement: "Evmos"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0049"
        replacement: "Fantom"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0050"
        replacement: "Moonbeam"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0001"
        replacement: "POKT"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0009"
        replacement: "Polygon"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_000B"
        replacement: "Polygon Arch"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0006"
        replacement: "Solana"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0058"
        replacement: "Metis"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0053"
        replacement: "Optimism"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_03DF"
        replacement: "DFK"
        target_label: "chain_name"
        action: "replace"
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_03CB"
        replacement: "SWIM"
        target_label: "chain_name"
        action: "replace"

      # Update metric name so all chains use the same metric name
      - source_labels: [ __name__ ]
        regex: "pocketcore_service_relay_count_for_0(.*)"
        replacement: "pocketcore_service_relay_count"
        target_label: "__name__"
        action: "replace"